xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 1 >  infiniteBeam_lena_diffuse/lena1.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 2 >  infiniteBeam_lena_diffuse/lena6.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 3 >  infiniteBeam_lena_diffuse/lena11.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 4 >  infiniteBeam_lena_diffuse/lena2.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 5 >  infiniteBeam_lena_diffuse/lena16.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 6 >  infiniteBeam_lena_diffuse/lena21.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 7 >  infiniteBeam_lena_diffuse/lena3.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 8 >  infiniteBeam_lena_diffuse/lena7.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 9 >  infiniteBeam_lena_diffuse/lena4.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 10 > infiniteBeam_lena_diffuse/lena5.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 11 > infiniteBeam_lena_diffuse/lena26.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 12 > infiniteBeam_lena_diffuse/lena12.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 13 > infiniteBeam_lena_diffuse/lena8.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 14 > infiniteBeam_lena_diffuse/lena31.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 15 > infiniteBeam_lena_diffuse/lena17.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 16 > infiniteBeam_lena_diffuse/lena9.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 17 > infiniteBeam_lena_diffuse/lena10.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 18 > infiniteBeam_lena_diffuse/lena13.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 19 > infiniteBeam_lena_diffuse/lena22.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 20 > infiniteBeam_lena_diffuse/lena14.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 21 > infiniteBeam_lena_diffuse/lena18.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 22 > infiniteBeam_lena_diffuse/lena15.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 23 > infiniteBeam_lena_diffuse/lena19.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 24 > infiniteBeam_lena_diffuse/lena20.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 25 > infiniteBeam_lena_diffuse/lena27.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 26 > infiniteBeam_lena_diffuse/lena23.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 27 > infiniteBeam_lena_diffuse/lena24.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 28 > infiniteBeam_lena_diffuse/lena25.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 29 > infiniteBeam_lena_diffuse/lena32.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 30 > infiniteBeam_lena_diffuse/lena28.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 31 > infiniteBeam_lena_diffuse/lena29.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 32 > infiniteBeam_lena_diffuse/lena30.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 33 > infiniteBeam_lena_diffuse/lena33.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 34 > infiniteBeam_lena_diffuse/lena34.csv
xlsx2csv --floatformat %.8e MC_gross_diffuse.xlsx -s 35 > infiniteBeam_lena_diffuse/lena35.csv
