xlsx2csv --floatformat %.8e MC_gross.xlsx -s 1 >  infiniteBeam_lena/lena1.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 2 >  infiniteBeam_lena/lena6.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 3 >  infiniteBeam_lena/lena11.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 4 >  infiniteBeam_lena/lena2.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 5 >  infiniteBeam_lena/lena16.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 6 >  infiniteBeam_lena/lena21.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 7 >  infiniteBeam_lena/lena3.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 8 >  infiniteBeam_lena/lena7.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 9 >  infiniteBeam_lena/lena4.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 10 > infiniteBeam_lena/lena5.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 11 > infiniteBeam_lena/lena26.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 12 > infiniteBeam_lena/lena12.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 13 > infiniteBeam_lena/lena8.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 14 > infiniteBeam_lena/lena31.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 15 > infiniteBeam_lena/lena17.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 16 > infiniteBeam_lena/lena9.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 17 > infiniteBeam_lena/lena10.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 18 > infiniteBeam_lena/lena13.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 19 > infiniteBeam_lena/lena22.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 20 > infiniteBeam_lena/lena14.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 21 > infiniteBeam_lena/lena18.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 22 > infiniteBeam_lena/lena15.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 23 > infiniteBeam_lena/lena19.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 24 > infiniteBeam_lena/lena20.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 25 > infiniteBeam_lena/lena27.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 26 > infiniteBeam_lena/lena23.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 27 > infiniteBeam_lena/lena24.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 28 > infiniteBeam_lena/lena25.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 29 > infiniteBeam_lena/lena32.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 30 > infiniteBeam_lena/lena28.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 31 > infiniteBeam_lena/lena29.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 32 > infiniteBeam_lena/lena30.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 33 > infiniteBeam_lena/lena33.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 34 > infiniteBeam_lena/lena34.csv
xlsx2csv --floatformat %.8e MC_gross.xlsx -s 35 > infiniteBeam_lena/lena35.csv
