xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 1 >  lena_diffuse/lena1.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 2 >  lena_diffuse/lena6.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 3 >  lena_diffuse/lena11.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 4 >  lena_diffuse/lena2.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 5 >  lena_diffuse/lena16.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 6 >  lena_diffuse/lena21.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 7 >  lena_diffuse/lena3.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 8 >  lena_diffuse/lena7.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 9 >  lena_diffuse/lena4.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 10 > lena_diffuse/lena5.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 11 > lena_diffuse/lena26.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 12 > lena_diffuse/lena12.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 13 > lena_diffuse/lena8.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 14 > lena_diffuse/lena31.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 15 > lena_diffuse/lena17.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 16 > lena_diffuse/lena9.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 17 > lena_diffuse/lena10.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 18 > lena_diffuse/lena13.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 19 > lena_diffuse/lena22.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 20 > lena_diffuse/lena14.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 21 > lena_diffuse/lena18.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 22 > lena_diffuse/lena15.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 23 > lena_diffuse/lena19.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 24 > lena_diffuse/lena20.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 25 > lena_diffuse/lena27.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 26 > lena_diffuse/lena23.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 27 > lena_diffuse/lena24.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 28 > lena_diffuse/lena25.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 29 > lena_diffuse/lena32.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 30 > lena_diffuse/lena28.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 31 > lena_diffuse/lena29.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 32 > lena_diffuse/lena30.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 33 > lena_diffuse/lena33.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 34 > lena_diffuse/lena34.csv
xlsx2csv --floatformat %.8e MC_diffuse.xlsx -s 35 > lena_diffuse/lena35.csv
