xlsx2csv --floatformat %.8e MC.xlsx -s 1 >  lena/lena1.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 2 >  lena/lena6.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 3 >  lena/lena11.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 4 >  lena/lena2.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 5 >  lena/lena16.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 6 >  lena/lena21.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 7 >  lena/lena3.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 8 >  lena/lena7.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 9 >  lena/lena4.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 10 > lena/lena5.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 11 > lena/lena26.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 12 > lena/lena12.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 13 > lena/lena8.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 14 > lena/lena31.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 15 > lena/lena17.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 16 > lena/lena9.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 17 > lena/lena10.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 18 > lena/lena13.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 19 > lena/lena22.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 20 > lena/lena14.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 21 > lena/lena18.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 22 > lena/lena15.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 23 > lena/lena19.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 24 > lena/lena20.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 25 > lena/lena27.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 26 > lena/lena23.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 27 > lena/lena24.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 28 > lena/lena25.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 29 > lena/lena32.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 30 > lena/lena28.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 31 > lena/lena29.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 32 > lena/lena30.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 33 > lena/lena33.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 34 > lena/lena34.csv
xlsx2csv --floatformat %.8e MC.xlsx -s 35 > lena/lena35.csv
